name: CI

on:
  push:
    branches: [master]
    paths-ignore: ['**.md']
  pull_request:
    types: [opened, synchronize]
    paths-ignore: ['**.md']

jobs:
  run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: src/github.com/${{ github.repository }}
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 1
        path: src/github.com/${{ github.repository }}
    - uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Build archives
      run: make archive
